# Generated by Django 4.2.8 on 2023-12-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carddata_imagedata_remove_postit_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='user',
        ),
        migrations.DeleteModel(
            name='CardData',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='ImageData',
        ),
    ]
